# This file was generated by GoReleaser. DO NOT EDIT.
class PutioSync < Formula
  desc "Put.io folder sync app"
  homepage "https://github.com/putdotio/putio-sync"
  version "2.0.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/putdotio/putio-sync/releases/download/v2.0.2/putio-sync_2.0.2_macos.tar.gz"
    sha256 "8f6253a05c0d10acaeab7913e368a31c8b9aeadb623bdebbf736f281b95e1109"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/putdotio/putio-sync/releases/download/v2.0.2/putio-sync_2.0.2_linux.tar.gz"
      sha256 "9c06d0f40b6a449879dcc77f744796a9b7c6d3df0a062f5206640bdf1b811db7"
    end
  end

  def install
    bin.install "putio-sync"
  end

  test do
    system "#{bin}/putio-sync -version"
  end
end
